### ISSUE TITLE
TMCM-1240

### ISSUE THREAD

**Issue by ahmad38faraz** [analogdevicesinc/tmcl_ros#3]
Hello,

Can we use this driver to control TMCM-1240? If not, is it possible to tweak the codes to accomodate TMCM-1240? What changes might be required in this case?

Thank you!

**Comment by mmaralit-adi** [comment]
Hi @ahmad38faraz - we have a planned upgrade which you can try for TMCM-1240, and for that upgrade, we don't expect that you need to additionally tweak the codes. It will be released by mid-next week. I'll notify you here once available.

**Comment by ahmad38faraz** [comment]
Hello @mmaralit-adi , is there any progress on this issue so far? thanks!

**Comment by mmaralit-adi** [comment]
Hello @ahmad38faraz - we finalized it in our internal repo today, planned release here in Github is tomorrow or the the day after that (July 26 or 27). Will tag you again here once done.

**Comment by mmaralit-adi** [comment]
Hi @ahmad38faraz, this is now committed at latest noetic branch (commit [4374d13](https://github.com/analogdevicesinc/tmcl_ros/commit/4374d1319f5d2175f40676262b64fabecf1010d7)). We are yet to tag that commit as v2.0.0. Please try and let us know if you encounter any problems.

**Comment by ahmad38faraz** [comment]
Thank you very much! I am excited to look into the package. 

I have TMCM-1240 (CANOpen) driver. I have a stepper motor which is not a trinamic stepper motor but compatible with the driver. I want to write hardware interface of this motor because it will be one of the joints of my robotic arm. So, essentially, I have to implement init(), read(), and write() functions for this motor.  I will go through the codes and will try to set it up. 

Thank you again!

**Comment by mmaralit-adi** [comment]
Closing now since TMCM-1240 as of v2.0.0-noetic.
